# Generated by Django 4.2.1 on 2023-05-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pro_url', models.CharField(max_length=10)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.categories')),
            ],
        ),
    ]
